name: fifteen
description: "Wacky puzzles as a cross-platform app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter


  provider: ^6.1.2
  google_mobile_ads: ^5.2.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#000000"
    theme_color: "#ff0000"

flutter:
  uses-material-design: true

  assets:
   - assets/images/icon.png
   - assets/images/header.png
   - assets/images/img1.png
   - assets/images/img2.png
   - assets/images/img3.png
   - assets/images/img4.png
   - assets/images/fruit0.png
   - assets/images/fruit1.png
   - assets/images/fruit2.png
   - assets/images/fruit3.png
   - assets/images/fruit4.png
   - assets/images/fruit5.png
   - assets/images/fruit6.png
   - assets/images/fruit7.png
   - assets/images/fruit8.png
   - assets/images/fruit9.png
   - assets/images/bg0.png
   - assets/images/bg1.png
   - assets/images/bg2.png
   - assets/images/bg3.png
   - assets/images/bg4.png
   - assets/images/bg5.png
  shaders:
   - shaders/test_fractal.frag
   - shaders/image_blur.frag
   - shaders/image_quad.frag
  