name: fifteen
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  shared_preferences: ^2.2.3
  google_mobile_ads: ^5.1.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#000000"
    theme_color: "#ff0000"

flutter:
  uses-material-design: true

  assets:
   - assets/images/icon.png
   - assets/images/header.png
   - assets/images/img.png
   - assets/images/img2.png
   - assets/images/img3.png
   - assets/images/img4.png
   - assets/images/img5.png
   - assets/images/placeholder1.png
   - assets/images/placeholder2.png
   - assets/images/placeholder3.png
   - assets/images/placeholder4.png
   - assets/images/placeholder5.png
   - assets/images/placeholder6.png
  shaders:
   - shaders/test_fractal.frag
   - shaders/image_blur.frag
   - shaders/image_quad.frag
  