name: fifteen
description: "Wacky puzzles as a cross-platform app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  google_mobile_ads: ^5.2.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  dart_mappable: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  build_runner: ^2.4.13
  dart_mappable_builder: ^4.2.3

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#000000"
    theme_color: "#ff0000"

flutter:
  uses-material-design: true

  assets:
   - assets/images/icon.png
   - assets/images/header.png
   
   - assets/images/photos/animal.jpg
   - assets/images/photos/avenue.jpg
   - assets/images/photos/beach.jpg
   - assets/images/photos/beach2.jpg
   - assets/images/photos/bee.jpg
   - assets/images/photos/cat.jpg
   - assets/images/photos/cat2.jpg
   - assets/images/photos/cat3.jpg
   - assets/images/photos/cat4.jpg
   - assets/images/photos/cat5.jpg
   - assets/images/photos/cat6.jpg
   - assets/images/photos/chipmunk.jpg
   - assets/images/photos/chipmunk2.jpg
   - assets/images/photos/dahlia.jpg
   - assets/images/photos/dahlia2.jpg
   - assets/images/photos/desert.jpg
   - assets/images/photos/drop.jpg
   - assets/images/photos/eurasian-squirrel.jpg
   - assets/images/photos/field.jpg
   - assets/images/photos/flower.jpg
   - assets/images/photos/mean-leash.jpg
   - assets/images/photos/milky-way.jpg
   - assets/images/photos/moon.jpg
   - assets/images/photos/mountains.jpg
   - assets/images/photos/muskrat.jpg
   - assets/images/photos/nature.jpg
   - assets/images/photos/plaid.jpg
   - assets/images/photos/rat.jpg
   - assets/images/photos/rat1.jpg
   - assets/images/photos/rat2.jpg
   - assets/images/photos/squirrel.jpg
   - assets/images/photos/squirrel2.jpg
   - assets/images/photos/straw-flower.jpg
   - assets/images/photos/wave.jpg

   - assets/boards/4-example.json
   - assets/boards/5-trivial.json
   - assets/boards/5-frame.json
   - assets/boards/6-split-example.json
   - assets/boards/7-less-trivial.json
   - assets/boards/8-square.json
   - assets/boards/9-classic.json
   - assets/boards/9-cubeception.json
   - assets/boards/9-cubes-hard.json
   - assets/boards/9-cubes-trivial.json
   - assets/boards/10-pentagon.json
   - assets/boards/12-hexagon.json
   - assets/boards/12-medium-cube.json
   - assets/boards/12-flipped-medium-cube.json
   - assets/boards/12-square-hard.json
   - assets/boards/12-squareception.json
   - assets/boards/12-two-rings.json
   - assets/boards/16-classic.json

  shaders:
   - shaders/test_fractal.frag
   - shaders/image_blur.frag
   - shaders/image_quad.frag
  