name: fifteen
description: "Wacky puzzles as a cross-platform app."
publish_to: 'none'

version: 2.0.3+5

environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  google_mobile_ads: ^5.2.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  dart_mappable: ^4.3.0
  async: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  build_runner: ^2.4.13
  dart_mappable_builder: ^4.2.3

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon512x512.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
   - assets/images/icon.png
   - assets/images/header.png
   - assets/images/photos/
   - assets/boards/

  shaders:
   - shaders/test_fractal.frag
   - shaders/image_blur.frag
   - shaders/image_quad.frag
  